// <auto-generated />
using System;
using Dnd_Inventory_API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dnd_Inventory_Logic.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20231010091349_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Dnd_Inventory_Logic.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Dnd_Inventory_Logic.Entities.SessionJoinKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid>("JoinKey")
                        .HasColumnType("char(36)");

                    b.Property<int?>("JoinKeyId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("UsesLeft")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JoinKeyId");

                    b.HasIndex("SessionId");

                    b.ToTable("JoinKeys");
                });

            modelBuilder.Entity("Dnd_Inventory_Logic.Entities.SessionUsers", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionUsers");
                });

            modelBuilder.Entity("Dnd_Inventory_Logic.Entities.SessionJoinKey", b =>
                {
                    b.HasOne("Dnd_Inventory_Logic.Entities.Session", null)
                        .WithMany("SessionJoinKeys")
                        .HasForeignKey("JoinKeyId");

                    b.HasOne("Dnd_Inventory_Logic.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Dnd_Inventory_Logic.Entities.SessionUsers", b =>
                {
                    b.HasOne("Dnd_Inventory_Logic.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Dnd_Inventory_Logic.Entities.Session", b =>
                {
                    b.Navigation("SessionJoinKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
