services:

  account-db:
    image: mongo
    container_name: Acount-mongo-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
      MONGO_INITDB_DATABASE: account-db
    ports:
      - '8080:27017'
    volumes:
      - mongo-db:/var/lib/mysql
      - ./mongo-db/init.sql:/docker-entrypoint-initmongo-db.d/init.sql

  mongo-express:
    image: mongo-express
    container_name: mongo-web
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopwd
      ME_CONFIG_MONGODB_URL: mongodb://root:mongopwd@account-db:27017/
    links:
      - account-db
    depends_on:
      - account-db 

  mysql-db:
    container_name: dnd-inventory-mysql
    image: mysql/mysql-server:latest
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=dndinventory
      - MYSQL_ROOT_PASSWORD=RootSqlHost
      - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql
      - ./mysql-db/init.sql:/docker-entrypoint-initmysql-db.d/init.sql

  mysql-test-db:
    container_name: dnd-test-inventory-mysql
    image: mysql/mysql-server:latest
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=dndtestinventory
      - MYSQL_ROOT_PASSWORD=RootSqlHost
      - MYSQL_ROOT_HOST=%
    ports:
      - '3307:3306'
    volumes:
      - mysql-test-db:/var/lib/mysql
      - ./mysql-test-db/init.sql:/docker-entrypoint-initmysql-test-db.d/init.sql

      
volumes:
  mysql-db:
    driver: local
  mysql-test-db:
    driver: local
  mongo-db:
    driver: local