# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on: [push, pull_request]

jobs:

  build:
    name: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore "Dnd Inventory/Dnd Inventory.sln"
    - name: Build
      run: dotnet build "Dnd Inventory/Dnd Inventory.sln" --no-restore
  unit_test:
    name: unit_test
    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Tests
      run: dotnet test "Dnd Inventory/Tests/Tests.csproj"

  integration_test:
    name: integration_test
    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3307
        container port: 3306
        mysql root password: 'dndtestinventory'
        mysql database: 'RootSqlHost'
          
    - name: Tests
      run: dotnet test "Dnd Inventory/Integration test/Integration test.csproj"
